create table if not exists tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    course text not null,
    description text not null,
    deadline timestamptz not null,
    difficulty text not null default 'Medium' check (difficulty in ('Low', 'Medium', 'High')),
    completed boolean not null default false,
    attachment_name text,
    attachment_path text,
    attachment_type text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists budget_entries (
    id bigint generated by default as identity primary key,
    title text not null default '',
    type text not null check (type in ('deposit', 'withdraw')),
    amount numeric(12, 2) not null check (amount > 0),
    reason text not null,
    status text not null default 'pending' check (status in ('pending', 'spent', 'cancelled')),
    wallet_id bigint,
    course text,
    contributor_id bigint,
    payer_names text not null default '[]',
    attachment_name text,
    attachment_path text,
    attachment_type text,
    created_at timestamptz not null default now()
);

create table if not exists wallets (
    id bigint generated by default as identity primary key,
    name text not null unique,
    course text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists contributors (
    id bigint generated by default as identity primary key,
    name text not null unique,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists budget_audit_events (
    id bigint generated by default as identity primary key,
    entry_id bigint references budget_entries(id) on delete set null,
    event_type text not null,
    actor text not null default 'system',
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table budget_entries add column if not exists wallet_id bigint references wallets(id) on delete set null;
alter table budget_entries add column if not exists course text;
alter table budget_entries add column if not exists contributor_id bigint references contributors(id) on delete set null;
alter table budget_entries add column if not exists payer_names text not null default '[]';
alter table budget_entries add column if not exists title text not null default '';
alter table budget_entries add column if not exists payees text not null default '[]';
alter table budget_entries add column if not exists purchased_items text not null default '[]';
alter table budget_entries add column if not exists attachment_name text;
alter table budget_entries add column if not exists attachment_path text;
alter table budget_entries add column if not exists attachment_type text;

create table if not exists announcements (
    id bigint generated by default as identity primary key,
    title text not null,
    body text not null,
    link_url text,
    attachment_name text,
    attachment_path text,
    attachment_type text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists poll_options (
    id bigint generated by default as identity primary key,
    announcement_id bigint not null references announcements(id) on delete cascade,
    label text not null,
    position integer not null default 0
);

create table if not exists poll_votes (
    id bigint generated by default as identity primary key,
    announcement_id bigint not null references announcements(id) on delete cascade,
    option_id bigint not null references poll_options(id) on delete cascade,
    school_id text not null,
    created_at timestamptz not null default now(),
    unique (announcement_id, school_id)
);

create table if not exists notes (
    id bigint generated by default as identity primary key,
    title text not null,
    course text not null,
    caption text not null,
    attachment_name text,
    attachment_path text,
    attachment_type text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists note_attachments (
    id bigint generated by default as identity primary key,
    note_id bigint not null references notes(id) on delete cascade,
    name text not null,
    path text not null,
    type text not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_tasks_deadline on tasks (completed, deadline, id);
create index if not exists idx_budget_entries_created_at on budget_entries (created_at desc, id desc);
create index if not exists idx_budget_entries_wallet_created on budget_entries (wallet_id, created_at desc, id desc);
create index if not exists idx_budget_audit_events_entry on budget_audit_events (entry_id, created_at desc, id desc);
create index if not exists idx_wallets_course on wallets (course);
create index if not exists idx_contributors_active on contributors (active, name);
create index if not exists idx_announcements_created_at on announcements (created_at desc, id desc);
create index if not exists idx_poll_options_announcement on poll_options (announcement_id, position, id);
create index if not exists idx_poll_votes_option on poll_votes (option_id);
create index if not exists idx_notes_created_at on notes (created_at desc, id desc);
create index if not exists idx_note_attachments_note on note_attachments (note_id, id);

create table if not exists no_class_exceptions (
    id bigint generated by default as identity primary key,
    date date not null,
    course text not null,
    created_at timestamptz not null default now(),
    unique (date, course)
);

create index if not exists idx_no_class_exceptions_date on no_class_exceptions (date);

create table if not exists assistant_actions (
    token_hash text primary key,
    tool_name text not null,
    arguments jsonb not null,
    expires_at timestamptz not null,
    used boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists assistant_audit_events (
    id bigint generated by default as identity primary key,
    tool_name text not null,
    arguments jsonb not null,
    status text not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_assistant_actions_expiry on assistant_actions (expires_at, used);
create index if not exists idx_assistant_audit_created on assistant_audit_events (created_at desc, id desc);

-- PostgreSQL/Supabase RAG storage. SQLite creates a text-only equivalent at runtime.
create extension if not exists vector;
create table if not exists note_chunks (
    id bigint generated by default as identity primary key,
    note_id bigint not null references notes(id) on delete cascade,
    chunk_index integer not null,
    content text not null,
    content_hash text not null,
    embedding vector(1536),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (note_id, chunk_index)
);
create index if not exists idx_note_chunks_note on note_chunks (note_id, chunk_index);
create index if not exists idx_note_chunks_embedding_hnsw on note_chunks using hnsw (embedding vector_cosine_ops) where embedding is not null;

insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', false)
on conflict (id) do nothing;

