create table if not exists tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    course text not null,
    description text not null,
    deadline timestamptz not null,
    difficulty text not null default 'Medium' check (difficulty in ('Low', 'Medium', 'High')),
    completed boolean not null default false,
    attachment_name text,
    attachment_path text,
    attachment_type text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists budget_entries (
    id bigint generated by default as identity primary key,
    type text not null check (type in ('deposit', 'withdraw')),
    amount numeric(12, 2) not null check (amount > 0),
    reason text not null,
    status text not null default 'pending' check (status in ('pending', 'spent', 'cancelled')),
    created_at timestamptz not null default now()
);

create table if not exists announcements (
    id bigint generated by default as identity primary key,
    title text not null,
    body text not null,
    link_url text,
    attachment_name text,
    attachment_path text,
    attachment_type text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists poll_options (
    id bigint generated by default as identity primary key,
    announcement_id bigint not null references announcements(id) on delete cascade,
    label text not null,
    position integer not null default 0
);

create table if not exists poll_votes (
    id bigint generated by default as identity primary key,
    announcement_id bigint not null references announcements(id) on delete cascade,
    option_id bigint not null references poll_options(id) on delete cascade,
    school_id text not null,
    created_at timestamptz not null default now(),
    unique (announcement_id, school_id)
);

create table if not exists notes (
    id bigint generated by default as identity primary key,
    title text not null,
    course text not null,
    caption text not null,
    attachment_name text,
    attachment_path text,
    attachment_type text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists note_attachments (
    id bigint generated by default as identity primary key,
    note_id bigint not null references notes(id) on delete cascade,
    name text not null,
    path text not null,
    type text not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_tasks_deadline on tasks (completed, deadline, id);
create index if not exists idx_budget_entries_created_at on budget_entries (created_at desc, id desc);
create index if not exists idx_announcements_created_at on announcements (created_at desc, id desc);
create index if not exists idx_poll_options_announcement on poll_options (announcement_id, position, id);
create index if not exists idx_poll_votes_option on poll_votes (option_id);
create index if not exists idx_notes_created_at on notes (created_at desc, id desc);
create index if not exists idx_note_attachments_note on note_attachments (note_id, id);

-- Create the private bucket used by the Flask server. The service-role key
-- bypasses these policies; the policies keep the bucket closed to browsers.
insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', false)
on conflict (id) do nothing;

