-- Run this once in the Supabase SQL Editor before deploying the Flask app.
create table if not exists public.no_class_exceptions (
    id bigint generated by default as identity primary key,
    date date not null,
    course text not null,
    created_at timestamptz not null default now(),
    unique (date, course)
);
create index if not exists idx_no_class_exceptions_date on public.no_class_exceptions (date);

alter table public.budget_entries add column if not exists title text not null default '';
alter table public.budget_entries add column if not exists payer_names text not null default '[]';
alter table public.budget_entries add column if not exists payees text not null default '[]';
alter table public.budget_entries add column if not exists purchased_items text not null default '[]';

create table if not exists public.assistant_actions (
    token_hash text primary key,
    tool_name text not null,
    arguments jsonb not null,
    expires_at timestamptz not null,
    used boolean not null default false,
    created_at timestamptz not null default now()
);
create table if not exists public.assistant_audit_events (
    id bigint generated by default as identity primary key,
    tool_name text not null,
    arguments jsonb not null,
    status text not null,
    created_at timestamptz not null default now()
);
create index if not exists idx_assistant_actions_expiry on public.assistant_actions (expires_at, used);
create index if not exists idx_assistant_audit_created on public.assistant_audit_events (created_at desc, id desc);

select to_regclass('public.no_class_exceptions') as no_class_exceptions_ready;