-- Run this once in the Supabase SQL Editor before deploying the Flask app.
create table if not exists public.no_class_exceptions (
    id bigint generated by default as identity primary key,
    date date not null,
    course text not null,
    created_at timestamptz not null default now(),
    unique (date, course)
);
create index if not exists idx_no_class_exceptions_date on public.no_class_exceptions (date);

alter table public.budget_entries add column if not exists title text not null default '';
alter table public.budget_entries add column if not exists payer_names text not null default '[]';
alter table public.budget_entries add column if not exists payees text not null default '[]';
alter table public.budget_entries add column if not exists purchased_items text not null default '[]';

create table if not exists public.assistant_actions (
    token_hash text primary key,
    tool_name text not null,
    arguments jsonb not null,
    expires_at timestamptz not null,
    used boolean not null default false,
    created_at timestamptz not null default now()
);
create table if not exists public.assistant_audit_events (
    id bigint generated by default as identity primary key,
    tool_name text not null,
    arguments jsonb not null,
    status text not null,
    created_at timestamptz not null default now()
);
create index if not exists idx_assistant_actions_expiry on public.assistant_actions (expires_at, used);
create index if not exists idx_assistant_audit_created on public.assistant_audit_events (created_at desc, id desc);

create extension if not exists vector;
create table if not exists public.note_chunks (
    id bigint generated by default as identity primary key,
    note_id bigint not null references public.notes(id) on delete cascade,
    chunk_index integer not null,
    content text not null,
    content_hash text not null,
    embedding vector(1536),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (note_id, chunk_index)
);
create index if not exists idx_note_chunks_note on public.note_chunks (note_id, chunk_index);
create index if not exists idx_note_chunks_embedding_hnsw on public.note_chunks using hnsw (embedding vector_cosine_ops) where embedding is not null;

create table if not exists public.interactive_sources (
    id bigint generated by default as identity primary key,
    source_key text not null unique,
    title text not null,
    course text not null,
    content text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create table if not exists public.interactive_source_chunks (
    id bigint generated by default as identity primary key,
    source_id bigint not null references public.interactive_sources(id) on delete cascade,
    chunk_index integer not null,
    content text not null,
    content_hash text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source_id, chunk_index)
);
create index if not exists idx_interactive_source_chunks_source on public.interactive_source_chunks (source_id, chunk_index);
create table if not exists public.interactive_examples (
    id bigint generated by default as identity primary key,
    title text not null,
    course text not null,
    content text not null,
    created_at timestamptz not null default now()
);
create index if not exists idx_interactive_examples_course on public.interactive_examples (course, created_at desc);

insert into public.interactive_sources (source_key, title, course, content)
values (
        'simple_interest_lesson',
        'Simple Interest Lesson',
        'Engr Econ',
        'Simple interest. Simple interest is calculated with I = P x r x t, where P is principal, r is the annual interest rate written as a decimal, and t is time in years. The future value is A = P + I. Ordinary simple interest uses a 30/360 day-count convention. Exact simple interest uses the actual elapsed days divided by 365. To solve a problem, identify the known values, convert the rate from percent to decimal and time to years, substitute into the formula, then check that the result is reasonable.'
)
on conflict (source_key) do nothing;
insert into public.interactive_source_chunks (source_id, chunk_index, content, content_hash)
select id, 0, content, md5(content)
from public.interactive_sources
where source_key = 'simple_interest_lesson'
    and not exists (select 1 from public.interactive_source_chunks where source_id = public.interactive_sources.id and chunk_index = 0);

select to_regclass('public.no_class_exceptions') as no_class_exceptions_ready;