use std::io::{Read,Write};
use std::net::{TcpListener,TcpStream};
use std::path::Path;
use serde::Deserialize;
use crate::{inference,model::Model};
#[derive(Deserialize)] struct RequestBody{text:String}
fn write_response(mut s:TcpStream,status:&str,body:&str){let _=write!(s,"HTTP/1.1 {}\r\nContent-Type: application/json\r\nAccess-Control-Allow-Origin: *\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",status,body.as_bytes().len(),body);}
fn handle(mut s:TcpStream,model:&Model){let mut buf=vec![0u8;65536];let mut n=0;let header_end;loop{if n==buf.len(){write_response(s,"413 Payload Too Large","{\"error\":\"request too large\"}");return;}let read=s.read(&mut buf[n..]).unwrap_or(0);if read==0{write_response(s,"400 Bad Request","{\"error\":\"incomplete request\"}");return;}n+=read;if let Some(end)=buf[..n].windows(4).position(|window|window==b"\r\n\r\n"){header_end=end+4;break;}}let (first,content_length)={let headers=String::from_utf8_lossy(&buf[..header_end]);let mut lines=headers.split("\r\n");let first=lines.next().unwrap_or("").to_owned();let content_length=lines.find_map(|line|line.split_once(':').and_then(|(name,value)|name.eq_ignore_ascii_case("Content-Length").then(||value.trim().parse::<usize>().ok())).flatten()).unwrap_or(0);(first,content_length)};if content_length>buf.len()-header_end{write_response(s,"413 Payload Too Large","{\"error\":\"request too large\"}");return;}while n<header_end+content_length{let read=s.read(&mut buf[n..]).unwrap_or(0);if read==0{write_response(s,"400 Bad Request","{\"error\":\"incomplete body\"}");return;}n+=read;}let req=String::from_utf8_lossy(&buf[..n]);if first.starts_with("OPTIONS "){write_response(s,"200 OK","{\"ok\":true}");return;}if first.starts_with("GET /health"){write_response(s,"200 OK","{\"ok\":true,\"service\":\"reinitialized\"}");return;}if first.starts_with("POST /predict"){let body=&req[header_end..header_end+content_length];match serde_json::from_str::<RequestBody>(body){Ok(b)=>{let out=inference::predict(model,&b.text);write_response(s,"200 OK",&serde_json::to_string(&out).unwrap());},Err(e)=>write_response(s,"400 Bad Request",&format!("{{\"error\":{}}}",serde_json::to_string(&e.to_string()).unwrap()))}return;}write_response(s,"404 Not Found","{\"error\":\"not found\"}");}
pub fn serve<P:AsRef<Path>>(model_path:P,bind:&str)->Result<(),Box<dyn std::error::Error>>{let model=Model::load(model_path)?;let listener=TcpListener::bind(bind)?;println!("Reinitialized server listening on http://{}",bind);println!("POST /predict {{\"text\":\"...\"}}");println!("GET  /health");for stream in listener.incoming(){match stream{Ok(s)=>handle(s,&model),Err(e)=>eprintln!("connection error: {e}")}}Ok(())}
